name: Issues workflow

on:
  issues:
    types: [opened]
    
jobs:
  respond:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/github-script@v1
      name: Responding to opened issue
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '👋 Thanks for reporting! This repository has limited activity due to being superseded by .Net core caching (IDistributedCache). So please be patient. Would happily accept pull requests though.'
          })
